# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: node:8

options:
  max-time: 4

clone: # the 'clone' section
  depth: 1 # the depth, in this case the clone will contain last commit

pipelines:
  branches:
    master:
      - step:
          deployment: production
          script:
            - >
              ssh bitbucket@direct.onova.co /bin/bash << EOF
                echo "connected to `hostname` as $USER";
                cd /var/www/webapp-drop &&
                git fetch &&
                git log -1 --oneline &&
                git reset --hard origin/master &&
                yarn &&
                GENERATE_SOURCEMAP=false nice -n 19 yarn build &&
                rm -rf dist/* &&
                cp -Rv build/* dist &&
                pm2 reload webapp-drop --silent --no-color &&
                curl --fail --silent --show-error -X POST "https://api.cloudflare.com/client/v4/zones/b4e61ffa14307ad26df097ce0cee2ca6/purge_cache" \
                  -H "X-Auth-Email: hello@givebox.xyz" \
                  -H "X-Auth-Key: $CLOUDFLARE_AUTH_KEY" \
                  -H "Content-Type: application/json" \
                  --data '{"purge_everything":true}'
